-- 039_import_services_catalog.sql
-- One-time bulk import of the clinic's existing services/tests price
-- list into the catalog (goods_services). Consult/Dental/Surgery/General
-- map to their matching existing Service subcategories; Test items map to
-- their matching existing Test subcategory (X-Ray/Ultrasound/PCR/Blood Test -
-- CBC/Urine) where the name matches, otherwise the new Test/Other subcategory
-- added in 038. 2 of 160 rows skipped for missing a price (Equipment Damage,
-- Spey - Dog Welfare (10%)) — add those by hand once priced. Run this ONCE —
-- re-running will insert duplicates, since goods_services has no unique
-- constraint on name.

insert into goods_services (name, main_category, subcategory_id, pricing_type, base_price)
values
    ('Avian - Candidatus Mycop Hem _MBG', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 450.0),
    ('Bacterial Culture (CVRL)', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 650.0),
    ('Bloods - Canine Ehrlichiosis -CVRL', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 450.0),
    ('Bloods - Canine Leishmaniosis - CVRL', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 335.0),
    ('Bloods - Canine leptospirosis CVRL', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 175.0),
    ('Bloods - Caninie Brucellosis _ CVRL', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 205.0),
    ('Bloods - CBC', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Blood Test - CBC'), 'flat', 165.0),
    ('Bloods - Thyroxine (T4)', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 265.0),
    ('Boarding - Cattery', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 60.0),
    ('Boarding - Cattery (2nd)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 45.0),
    ('Brucella Canis IFAT test (CVRL)', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 600.0),
    ('Castration Cat - Welfare', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 200.0),
    ('Catherterisation', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 165.0),
    ('Catheter', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 55.0),
    ('Cauterization', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 85.0),
    ('Consult', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Consults'), 'flat', 170.0),
    ('Consult  - Welfare', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Consults'), 'flat', 140.0),
    ('Consult - Artifical Insemination', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Consults'), 'flat', 300.0),
    ('Consult - Extended', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Consults'), 'flat', 60.0),
    ('Consult - Non - Scheduled Surcharge', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Consults'), 'flat', 55.0),
    ('Consult primo vacc', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Consults'), 'flat', 200.0),
    ('Consult vacc', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Consults'), 'flat', 145.0),
    ('Cortisol Test (CVRL)', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 300.0),
    ('Cremation >25kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 1250.0),
    ('Cremation 0-5kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 725.0),
    ('Cremation 11-25kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 1050.0),
    ('Cremation 6-10kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 850.0),
    ('Cruciate Repair Set', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 125.0),
    ('Culture & Sensitivety - CVRL', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 550.0),
    ('Dental - clean teeth', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Dental'), 'flat', 55.0),
    ('Dental - puppy tooth removal', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Dental'), 'flat', 55.0),
    ('Dental extraction', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Dental'), 'flat', 80.0),
    ('Dental polish', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Dental'), 'flat', 80.0),
    ('Descaling (15 min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Dental'), 'flat', 165.0),
    ('Dew claws bony', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 110.0),
    ('Dew claws flesh', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 55.0),
    ('Disposal <25kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 100.0),
    ('Disposal 0-5 kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 50.0),
    ('Disposal 11-25 kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 85.0),
    ('Disposal 6-10 kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 65.0),
    ('Distemper Test', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 165.0),
    ('Ehrlichia test', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 165.0),
    ('Euthanasia  6-10 kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 330.0),
    ('Euthanasia <25kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 550.0),
    ('Euthanasia 0-5 kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 220.0),
    ('Euthanasia 11-25 kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 440.0),
    ('Fecal Test - CVRL', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 265.0),
    ('FeLV FIV Corona (trio)', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 195.0),
    ('FIP Test', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 165.0),
    ('FIV/FeLV Test', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 165.0),
    ('Fluorescine Test', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 65.0),
    ('Gastroscopy (per 15 mins)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 275.0),
    ('Giadra/Parvo Combo', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 260.0),
    ('Giardia test', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 175.0),
    ('Grooming (per 15 min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 80.0),
    ('Health Cert - Export', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Consults'), 'flat', 185.0),
    ('Heartworm AG ELISA', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 100.0),
    ('Hematocrit (HTC) Test', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 50.0),
    ('Hospitalisation - Dog (p/day) Dog', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 180.0),
    ('Hospitalisation - L/term (p/day)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 75.0),
    ('Hospitalisation - Small Animal (per day)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 60.0),
    ('Hospitalisation - Welfare (p/day)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 100.0),
    ('House Call', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Consults'), 'flat', 400.0),
    ('I-Glo Fluorescein Sodium', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 37.5),
    ('ICU - Incubator (p/day)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 50.0),
    ('Insemination/semen collection', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 275.0),
    ('Intravenous fluids extra bottle 1000ml', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 110.0),
    ('Late Payment Penalty', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 20.0),
    ('Leptospira MAT test (CVRL)', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 300.0),
    ('Naso-Gastric Tube', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 165.0),
    ('Observation/overstay - Cat', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 60.0),
    ('On heat supplement', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 60.0),
    ('Orthopedic Wire', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 110.0),
    ('Out of hours drop off/pick up surbcharge', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 40.0),
    ('Overnight  - Cat', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 60.0),
    ('Overnight - Dog', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 95.0),
    ('Panleukopenia Ant. Test ^', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 165.0),
    ('Partial Payment Administration', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 20.0),
    ('Parvo cleaning sub (per day)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 75.0),
    ('Parvo Test', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 165.0),
    ('PawNovo PCR - Anemia 4 Plex', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'PCR'), 'flat', 250.0),
    ('PawNovo PCR - Diarrhea 5 Plex', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'PCR'), 'flat', 350.0),
    ('PawNovo PCR - Respiratory 5 Plex', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'PCR'), 'flat', 350.0),
    ('PawNovo PCR - Respiratory 6 Plex', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'PCR'), 'flat', 450.0),
    ('PawNovo PCR - Toxoplasma', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'PCR'), 'flat', 250.0),
    ('Pawprint  + name (CVRL)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 225.0),
    ('Pawprint only (CVRL)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 150.0),
    ('Pregnant supplement', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 200.0),
    ('Rabies Antibody (FAVN) - CVRL', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 1275.0),
    ('Sample Transportation (CVRL)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 150.0),
    ('Schirmer Tear Test', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 40.0),
    ('Skin CU woods, scrape & stain', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 75.0),
    ('Spey - Cat Welfare', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 440.0),
    ('Spey Cat - Pre Heat', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 510.0),
    ('Spot Panel (+ Sample Permit)', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 900.0),
    ('Stronghold Application', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 55.0),
    ('subcutanous fluids', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 80.0),
    ('Surgery - Extented (15 min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 365.0),
    ('Surgery Orthopedic 15 min', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 485.0),
    ('Thoracoenthesis', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 75.0),
    ('Transportation   p/KM', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 2.5),
    ('Ultrasound', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Ultrasound'), 'flat', 200.0),
    ('Ultrasound with Report', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Ultrasound'), 'flat', 375.0),
    ('Uricult Vet Test', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 165.0),
    ('VacciCheck - Canine HPD', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 175.0),
    ('X-ray Barium Contrast', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'X-Ray'), 'flat', 150.0),
    ('Anest cat (30min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 120.0),
    ('Anest <10kg (30min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 140.0),
    ('Anest 10<25kg (30min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 180.0),
    ('Anest 26<40kg (30min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 210.0),
    ('Anest >41kg (30min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 245.0),
    ('Sedation cat +rev', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 180.0),
    ('Sedation <10kg + rev', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 210.0),
    ('Sedation10-25kg + rev', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 240.0),
    ('Sedation 26-40kg + rev', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 300.0),
    ('Sedation >41kg + rev', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 360.0),
    ('Castration cat', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 265.0),
    ('Castration dog <10kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 620.0),
    ('Castration dog 11-25kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 800.0),
    ('Castration dog 26-40kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 930.0),
    ('Castration dog >41kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 1115.0),
    ('Spey cat', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 565.0),
    ('Spey dog <10kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 860.0),
    ('Spey dog10-25kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 1045.0),
    ('Spey dog 26-40kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 1175.0),
    ('Spey dog >41kg', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 1415.0),
    ('Surgery Sterile (15 min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 300.0),
    ('Surgery non Sterile (15 min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 155.0),
    ('Absces small', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 120.0),
    ('Absces medium', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 155.0),
    ('Absces large', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Surgeries'), 'flat', 180.0),
    ('X-ray  - 1st View', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'X-Ray'), 'flat', 300.0),
    ('X-ray  - additional views', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'X-Ray'), 'flat', 120.0),
    ('Consult small', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Consults'), 'flat', 60.0),
    ('Consult small pets', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Consults'), 'flat', 115.0),
    ('Express anal glands', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 40.0),
    ('Clip nails', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 40.0),
    ('Intraveneous fluids (start)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 275.0),
    ('Intraveneous fluids extra bottle 500ml', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 80.0),
    ('Clean ears small', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 40.0),
    ('Clean ears large', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 60.0),
    ('Bandage small', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 80.0),
    ('Bandage medium', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 110.0),
    ('Bandage large', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 130.0),
    ('Biopsy', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 280.0),
    ('Bloods - Critical Care', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 215.0),
    ('Bloods - Comprehensive', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 325.0),
    ('Microscopy', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 45.0),
    ('Microscopy + staining', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 80.0),
    ('Urine small + sg', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Urine'), 'flat', 70.0),
    ('Dental cat (15min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Dental'), 'flat', 220.0),
    ('Dental dog <10kg (15min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Dental'), 'flat', 275.0),
    ('Dental dog 10<25kg (15min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Dental'), 'flat', 330.0),
    ('Dental dog 26<40kg (15min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Dental'), 'flat', 385.0),
    ('Dental dog >41kg (15min)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Dental'), 'flat', 495.0),
    ('Hospitalisation - Cat (p/day)', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'General'), 'flat', 120.0),
    ('Autopsy Small animal (in house)', 'test', (select id from catalog_subcategories where main_category = 'test' and name = 'Other'), 'flat', 100.0),
    ('Consult second', 'service', (select id from catalog_subcategories where main_category = 'service' and name = 'Consults'), 'flat', 115.0);
